export const siteConfig = {
  title: "「Where would you like to go?」",
  subtitle: "curated links & socials by mphstar",
  footerLeft: "Built with ❤️",
  footerRight: "mphstar",
  links: [
    {
      id: 1,
      number: "05",
      label: "My Website",
      username: "mphstar.my.id",
      url: "https://www.mphstar.my.id/",
      image: "/images/character_website.png",
      align: "left",
      hoverClass: "hover:shadow-[0_0_30px_rgba(34,197,94,0.45)] hover:border-emerald-400/60",
      accentColor: "#10b981", // emerald
      glassesStyle: "round-clear",
      description: "Personal blog & portfolio",
    },
    {
      id: 2,
      number: "12",
      label: "TikTok",
      username: "@mphstar",
      url: "https://www.tiktok.com/@mphstar",
      image: "/images/character_tiktok.png",
      align: "right",
      hoverClass: "hover:shadow-[0_0_30px_rgba(168,85,247,0.45)] hover:border-purple-400/60",
      accentColor: "#a855f7", // purple
      glassesStyle: "round-sunglasses",
      description: "Short clips & moments",
    },
    {
      id: 3,
      number: "15",
      label: "Sociabuzz",
      username: "mphstar",
      url: "https://sociabuzz.com/mphstar/tribe?_ref=linkbio",
      image: "/images/character_sociabuzz.png",
      align: "left",
      hoverClass: "hover:shadow-[0_0_30px_rgba(234,179,8,0.45)] hover:border-amber-400/60",
      accentColor: "#eab308", // amber
      glassesStyle: "sporty",
      description: "Support my work",
    },
    {
      id: 4,
      number: "16",
      label: "GitHub",
      username: "@mphstar",
      url: "https://github.com/mphstar",
      image: "/images/character_github.png",
      align: "right",
      hoverClass: "hover:shadow-[0_0_30px_rgba(59,130,246,0.45)] hover:border-blue-400/60",
      accentColor: "#3b82f6", // blue
      glassesStyle: "hexagonal",
      description: "My repositories & code",
    },
    {
      id: 5,
      number: "18",
      label: "Roblox",
      username: "mphstar",
      url: "https://www.roblox.com/users/1738159625/profile",
      image: "/images/character_roblox.png",
      align: "left",
      hoverClass: "hover:shadow-[0_0_30px_rgba(244,63,94,0.45)] hover:border-rose-400/60",
      accentColor: "#f43f5e", // rose
      glassesStyle: "wireframe",
      description: "Roblox profile",
    },
    {
      id: 6,
      number: "20",
      label: "Discord Server",
      username: "Join Server",
      url: "https://discord.gg/gszbAyNU5p",
      image: "/images/character_discord.png",
      align: "right",
      hoverClass: "hover:shadow-[0_0_30px_rgba(88,101,242,0.45)] hover:border-indigo-400/60",
      accentColor: "#5865f2", // discord blurple
      glassesStyle: "round-clear",
      description: "Join my discord server",
    },
  ]
};
